// Auto-generated by scripts/indexer.js
window.GALLERY_DATA = {
    ALBUMS: [
    {
        "id": "a1",
        "title": "Artes",
        "description": "Auto-generated album for Artes",
        "coverPhotoId": "a1_p1",
        "tags": [
            "Auto"
        ],
        "rarity": "epic",
        "creationDate": "2026-04-26"
    },
    {
        "id": "a2",
        "title": "Conceitos",
        "description": "Auto-generated album for Conceitos",
        "coverPhotoId": "a2_p1",
        "tags": [
            "Auto"
        ],
        "rarity": "aurora",
        "creationDate": "2026-04-26"
    },
    {
        "id": "a3",
        "title": "Testes",
        "description": "Auto-generated album for Testes",
        "coverPhotoId": "a3_p1",
        "tags": [
            "Auto"
        ],
        "rarity": "aurora",
        "creationDate": "2026-04-26"
    }
],
    PHOTOS: {
    "a1": [
        {
            "id": "a1_p1",
            "filename": "gallery/Artes__epic/arte1.jpg",
            "name": "arte1",
            "uploadDate": "2026-04-26T20:58:23.559Z",
            "fileSize": "0.0 KB",
            "width": 0,
            "height": 0
        }
    ],
    "a2": [
        {
            "id": "a2_p1",
            "filename": "gallery/Conceitos__aurora/img1.jpg",
            "name": "img1",
            "uploadDate": "2026-04-26T20:41:18.146Z",
            "fileSize": "0.0 KB",
            "width": 0,
            "height": 0
        }
    ],
    "a3": [
        {
            "id": "a3_p1",
            "filename": "gallery/Testes__aurora/foto1.jpg",
            "name": "foto1",
            "uploadDate": "2026-04-26T20:58:23.555Z",
            "fileSize": "0.0 KB",
            "width": 0,
            "height": 0
        },
        {
            "id": "a3_p2",
            "filename": "gallery/Testes__aurora/foto2.png",
            "name": "foto2",
            "uploadDate": "2026-04-26T20:58:23.559Z",
            "fileSize": "0.0 KB",
            "width": 0,
            "height": 0
        }
    ]
}
};
