const fs = require('fs');
const path = require('path');

const galleryDir = path.join(__dirname, '../assets/gallery');
const outputJsPath = path.join(__dirname, '../js/gallery-data.js');

if (!fs.existsSync(galleryDir)) {
    fs.mkdirSync(galleryDir, { recursive: true });
}

const albums = [];
const photos = {};

const validExtensions = ['.png', '.jpg', '.jpeg', '.webp'];

const dirs = fs.readdirSync(galleryDir, { withFileTypes: true });

let albumIndex = 1;

for (const dir of dirs) {
    if (dir.isDirectory()) {
        const albumPath = path.join(galleryDir, dir.name);
        let albumTitle = dir.name;
        let rarity = 'common';

        const rarityMatch = dir.name.match(/__(common|rare|epic|legendary|aurora)$/i);
        if (rarityMatch) {
            rarity = rarityMatch[1].toLowerCase();
            albumTitle = dir.name.replace(rarityMatch[0], '');
        }

        const albumId = `a${albumIndex++}`;

        const files = fs.readdirSync(albumPath);
        const albumPhotos = [];

        let photoIndex = 1;
        for (const file of files) {
            const ext = path.extname(file).toLowerCase();
            if (validExtensions.includes(ext)) {
                const photoId = `${albumId}_p${photoIndex++}`;
                const stat = fs.statSync(path.join(albumPath, file));

                albumPhotos.push({
                    id: photoId,
                    filename: `gallery/${dir.name}/${file}`,
                    name: file.replace(ext, ''),
                    uploadDate: stat.birthtime.toISOString(),
                    fileSize: (stat.size / 1024).toFixed(1) + ' KB',
                    width: 0,
                    height: 0
                });
            }
        }

        if (albumPhotos.length > 0) {
            albums.push({
                id: albumId,
                title: albumTitle,
                description: `Auto-generated album for ${albumTitle}`,
                coverPhotoId: albumPhotos[0].id,
                tags: ['Auto'],
                rarity: rarity,
                creationDate: new Date().toISOString().split('T')[0]
            });
            photos[albumId] = albumPhotos;
        }
    }
}

const jsContent = `// Auto-generated by scripts/indexer.js\nwindow.GALLERY_DATA = {\n    ALBUMS: ${JSON.stringify(albums, null, 4)},\n    PHOTOS: ${JSON.stringify(photos, null, 4)}\n};\n`;

fs.writeFileSync(outputJsPath, jsContent, 'utf-8');
console.log(`[SUCESSO] Indexador concluído! Foram encontrados ${albums.length} álbuns.`);
